### ISSUE TITLE
Editor Preview breaks on mid-sized browser widths

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/goggles.webmaker.org#147]
Editor preview is either broken or intentionally hidden on screens with a width less than 890px. This will impact onboarding https://github.com/MozillaFoundation/plan/issues/241

Quick fix: the column header should be hidden. It seems like a broken tab. 

![screenshot 2015-01-20 16 59 50](https://cloud.githubusercontent.com/assets/53411/5827241/cef2faaa-a0c6-11e4-84d5-823b50cbe8c3.png)

**Comment by xmatthewx** [comment]
cc @Pomax @secretrobotron

**Comment by Pomax** [comment]
closing this as "after the revamp, that is no longer what the goggles dialog looks like"
