### ISSUE TITLE
Suggestions for changing string

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/goggles.webmaker.org#150]
"Instantly publish your remix to a URL that anyone can view."
Sounds like anyone can view the URL.

Maybe change to something like:
"Instantly publish your remix to get a URL so anyone can view your make."

**Comment by scootergrisen** [comment]
"Deactivate goggles" > "Deactivate Goggles" or maybe "Deactivate X-Ray Goggles".

**Comment by scootergrisen** [comment]
<div>That <code>&lt;${tagName}&gt;</code> element has too many nested elements inside of it for goggles to remix. Try selecting some of its content instead!</div>

Maybe change "goggles" to "Goggles ?

**Comment by scootergrisen** [comment]
"With X-Ray Goggles now activated, mouse around the page. Notice how images and text are highlighted with colors?"

Perhaps "mouse" should be "cursor".

**Comment by Pomax** [comment]
"to mouse around" is a verb action. There is no "to cursor around" in English.

**Comment by scootergrisen** [comment]
I meant like this:
"With X-Ray Goggles now activated, move the cursor around the page. Notice how images and text are highlighted with colors?"

The user might not be using a mouse, but some other input device to move the cursor.

**Comment by scootergrisen** [comment]
Change "ray" to "Ray" in these strings:
"Activate X-ray Goggles"
"X-ray Goggles"
"Set up X-ray Goggles"
"X-ray Goggles"

**Comment by scootergrisen** [comment]
These two strings talk about changing the filenavn, but in one case its without "/" and the other case has "/" in the beginning.

Maybe they should be the same ?

    "from shapes.jpg to blur.jpg"
    "Change <img src="/shapes.jpg"> to <img src="/blur.jpg">"

**Comment by Pomax** [comment]
the landing page for goggles is getting switched over to what is on https://webmaker.mofostaging.net/en-US/goggles now, so it's better to file strings issues on that site over on webmaker.org (we're removing everything webpage-related from here, and will use it exclusively for the goggles library)
