### ISSUE TITLE
Goggles fails to publish

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/goggles.webmaker.org#151]
I've tried twice, but Goggles fails to publish a remix of the Goggles landing page. 

 2. https://goggles.webmaker.org/
 3. activate goggles
 4. edit a heading
 5. `Publish`
 6. (modal appears) `Publish to Internet`
 7. error message appears

![screenshot 2015-01-22 11 58 38](https://cloud.githubusercontent.com/assets/53411/5860361/e212bb34-a22e-11e4-9f0c-a7d05cdd1b56.png)

cc @secretrobotron @Pomax

**Comment by adamlofting** [comment]
I'm seeing the same for webmaker account `adamlofting`.  (just mentioning in case it's not universal and you need extra test cases.)

**Comment by secretrobotron** [comment]
Thanks @adamlofting . What was the new account you used?

Error occurred for me too, with `secretrobotron`. Pretty opaque error reporting:
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

Would be useful to check logs. @jdotpz anything you can tell us?

**Comment by jdotpz** [comment]
Did you look at the logs?

**Comment by secretrobotron** [comment]
@jdotpz sorry, I don't think I can. Where do I do that?

**Comment by jdotpz** [comment]
Still on loggins.

{
  "_index": "logstash-2015.01.27",
  "_type": "logs",
  "_id": "Rdgs6sviSdWNIBWGdpbOQQ",
  "_score": null,
  "_source": {
    "host": "i-95e3edb8",
    "short_message": "Outgoing Response: HTTP 500 /publish (1515 ms)",
    "facility": "goggles-production",
    "@version": "1",
    "@timestamp": "2015-01-27T08:14:36.085Z",
    "source_host": "10.140.18.164",
    "url": "/publish",
    "responseTime": 1515,
    "res.statusCode": 500,
    "tags": [
      "gelf_message"
    ]
  },
  "sort": [
    1422346476085,
    1422346476085
  ]
}

{
  "_index": "logstash-2015.01.27",
  "_type": "logs",
  "_id": "nTIGhz19QcavivGp5cOgnw",
  "_score": null,
  "_source": {
    "host": "i-f2f0761c",
    "short_message": "Outgoing Response: HTTP 200 /verify (4 ms)",
    "facility": "goggles-production",
    "@version": "1",
    "@timestamp": "2015-01-27T08:14:33.586Z",
    "source_host": "10.65.21.226",
    "url": "/verify",
    "responseTime": 4,
    "res.statusCode": 200,
    "tags": [
      "gelf_message"
    ]
  },
  "sort": [
    1422346473586,
    1422346473586
  ]
}

Those two messages are an example of logs I see together.

**Comment by jdotpz** [comment]
https://loggins.mofoprod.net/#/dashboard/elasticsearch/Goggles-Production is a view I just threw up to allow for easier digestion of these logs.

**Comment by Pomax** [comment]
Looking at https://github.com/mozilla/goggles.webmaker.org/blob/master/app.js#L238, I think we're still using login2 instead of login3 for goggles... Filed #164 to address this O_O

**Comment by secretrobotron** [comment]
Niiiice.

**Comment by Pomax** [comment]
less severe than expected (front-end issue only), still a thing that needs fixin'
