### ISSUE TITLE
Redesign Goggles modal

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/goggles.webmaker.org#152]
I have a few UX concerns with the modal used by X-ray Goggles for making an edit to an element. 

 - the modal blocks content and instructions 
   - users need to learn copy-paste via shortcuts or right-click in order to use goggles for the first time
 - the preview only works on large screens
 - `preview` heading looks like a 3rd tab next to `basic` & `advanced`
 - choice between `basic` and `advanced` might confuse and intimidate users
 - branding, features, & layout create a very visually noisy experience for some trying to understand and remember a new language 
 - `save changes` button might scare a user who doesn't want to break things    

![screenshot 2015-01-22 13 28 11](https://cloud.githubusercontent.com/assets/53411/5861779/8ba32ade-a23a-11e4-988e-21b30aef783a.png)

**Comment by xmatthewx** [comment]
To improve the UX with a minimal amount of revision, I propose addition by way of subtraction. 

 - reduce modal to a single textarea + 2 buttons
 - reduce modal to small panel with position fixed to the bottom of browser window
 - remove preview
 - remove advanced view
 - remove branding

Below are a few mockups. Comment here or inline [via Redpen](https://redpen.io/wk02fef90977a64473). 

![gogglesmodal](https://cloud.githubusercontent.com/assets/53411/5861909/97afc26e-a23b-11e4-8512-668ea0b03c9a.png)

Supports work to improve onboarding: https://github.com/MozillaFoundation/plan/issues/241

@cassiemc @Pomax @secretrobotron @thisandagain

**Comment by secretrobotron** [comment]
Nice!
A couple questions:
- Why is "Insert HTML" better than "Save"?
- Are we keeping the basic mode's restrictions on what you're allowed to edit, or just letting people edit the entire block of text?
- Maybe a visual indicator to show you what you're currently editing?

**Comment by cassiemc** [comment]
Love idea of addition by way of subtraction, nice thinking @xmatthewx.

I like the transparency version. And +1 to @secretrobotron's points above – like the idea of highlighting which element is being edited. A stepping stone to something like firebug. 
And +1 to 'insert html' being MORE intimidating than 'save'.

**Comment by xmatthewx** [comment]
> Why is "Insert HTML" better than "Save"?

Users are here to play and have very little context. "Save" begs the questions: Where am I saving this? Who will see this? Will it break the NY Times homepage? Will homeland security take me away? 

"Insert" or something similar suggests that the user's edit will be inserted and visible on the page. Some options: Update, Change, Insert, Insert html, _Make it so_, ...

> Are we keeping the basic mode's restrictions

I think that Basic is more approachable for our primary users. If we had better analytics, we could see how many people actually use Advanced. Not sure that advanced people need or want x-ray goggles. I could be totally on wrong on this. 

> ... visual indicator

Agreed. I assumed the Goggles box of highlight color would persist after an element is clicked. But, it appears that it is dropped.

**Comment by xmatthewx** [comment]
Nice to haves:
 - Keep element highlighted until after a change is submitted
 - Or... Live preview. Update the page as a user edits

**Comment by secretrobotron** [comment]
> Users are here to play and have very little context.

Good call. "Update"? "Ok"? "Done"?

> Update the page as a user edits

Love that idea too, but it might be hard to spot.

**Comment by cassiemc** [comment]
I like 'update'

**Comment by secretrobotron** [comment]
@xmatthewx ok to close now? implementation under way
