### ISSUE TITLE
Design QA for new goggles landing

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/goggles.webmaker.org#153]
- [x] desktop: new goggles modal: look & feel
- [x] desktop: landing page: look & feel
- [x] ~~mobile view~~

File your feedback as issues within this repo and make sure it goes in the Webmaker On-boarding milestone.

/cc @xmatthewx

**Comment by secretrobotron** [comment]
Note: needs to incorporate the thoughts of a Hive organizer/member. They need to know this change is coming and feel comfortable using the new design.

**Comment by xmatthewx** [comment]
@vazquez reviewed earlier today. R?

**Comment by vazquez** [comment]
Hey guys, has this been coded yet? Is there a URL?

**Comment by secretrobotron** [comment]
@vazquez yessir. @Pomax has been working on it.
* https://radiant-retreat-8672.herokuapp.com/en-US/goggles
* https://radiant-retreat-8672.herokuapp.com/en-US/goggles/install

**Comment by vazquez** [comment]
Perfect :) I'll take a look and file issues!
