### ISSUE TITLE
Functionality QA for new goggles landing

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/goggles.webmaker.org#155]
Site we're testing: https://webmaker.mofostaging.net/en-US/goggles

File your feedback as issues within this repo and make sure it goes in the Webmaker On-boarding milestone.

## Functional Testing
- **Cross-browser testing**
  - **Desktop**
    - [ ] Chrome (Latest - 2)
    - [ ] Firefox (Latest - 2)
    - [ ] Internet Explorer (10+)
    - [ ] Safari (7+)
- [ ] Check layout on common variation of screen resolutions

#### Old goggles functionality
- [ ] Can delete elements on the page
- [ ] Can see and manipulate the content of any element on the page
  - [ ] by clicking on elements
  - [ ] by pressing "R" to remix
- [ ] Can publish a remixed page
  - [ ] Signup/Login worked while doing this
- [ ] Undo/Redo are still in tact
- [ ] Menu buttons work

#### New goggles functionality
- [ ] Elements update automatically when edited
- [ ] Clicking on an element reveals editor at the bottom of the screen
- [ ] "Help" link works (expands and reveals some tips)
- [ ] "Set up goggles" link goes to new page

#### Set up goggles
- [ ] Video is informative for installing goggles (THIS ISN'T DONE YET) cc @LucyeoH 
- [ ] Able to install goggles by dragging link to bookmarklet bar

## Graphical Objects
- [ ] Is the static text clear, concise, and meaningful?
- [ ] Are all static text words spelled out (correctly!) and abbreviations used only when space is limited?
- [ ] Is static text capitalized according to Webmaker standards?
- [ ] Do buttons follow the Webmaker standards for size and position?

## GUI Operation
- [ ] Are standards followed for mouse and keyboard navigation, manipulation, and interaction (e.g., TAB, SHIFT+TAB, double-click, selection of elements and objects, drag and drop)?
- [ ] Is the cursor changed to indicate when the user tries to take inappropriate action (e.g., hover)?

/cc @Pomax

**Comment by secretrobotron** [comment]
Note: needs to include a Hive organizer/member. They need to know this change is coming and feel comfortable using the new design.

**Comment by secretrobotron** [comment]
Jonathan from DHF can help here.

**Comment by secretrobotron** [comment]
@Pomax do you mind checking these?

## Performance
- [ ] Check image optimization
- [ ] Check total page/download time
- [ ] Toggle Network pane in Developer Tools (Command + Option + Q). Click on Reload. You will see something that looks like this: https://www.dropbox.com/s/r0fhsppf5bph56t/Screenshot%202014-12-19%2011.46.18.png?dl=0. Keep an eye out for any long-lasting requests or huge image sizes.

**Comment by secretrobotron** [comment]
Starting to appeal to people to start doing this today.

**Comment by ScottDowne** [comment]
Can delete elements on the page - not working for me.

**Comment by secretrobotron** [comment]
@ScottDowne please file.

**Comment by LucyeoH** [comment]
I tried this! Here are my findings: 

Old goggles functionality
    * Can delete elements on the page - Not working for me. I tried deleting the header and the background image and neither of them deleted. (I think @ScottDowne filed this) 
    * Can see and manipulate the content of any element on the page - If I click on something and then hit update and try and click on the same thing again it doesn't work until I try and click something else and then come back to it. (@ScottDowne filed) 
        by clicking on elements
        by pressing "R" to remix - it works! 
    * Can publish a remixed page - If I try and publish without being signed in it EXPLODES! (I filed a bug for this)  [screen shot 2015-02-09 at 1 40 06 pm](https://cloud.githubusercontent.com/assets/8070833/6112884/48fe38ce-b061-11e4-8a46-dfbeec878216.png)

    * Signup/Login worked while doing this - If X-Ray Goggles are activated you can't click the sign-in button, if you try and publish without signing in the page explodes, otherwise the login works fine. I think that's covered in my last bug. 
    Undo/Redo are still in tact- it works but it brings things back letter by letter, which is kind of painful.... 
    Menu buttons work - indeed they do! But the goggles menu is somewhat obscured by the scroll bar on my mac (screen shot here: [screen shot 2015-02-09 at 1 59 50 pm](https://cloud.githubusercontent.com/assets/8070833/6113270/02bfc37a-b064-11e4-89f4-05c8cb3b325f.png)

New goggles functionality

    *Elements update automatically when edited - Fact! 
    *Clicking on an element reveals editor at the bottom of the screen - True! 
    *"Help" link works (expands and reveals some tips)- the phrase for H "this help reference" is a bit confusing maybe "open help" would make more sense. Also "view/edit computed style of selected element" means nothing to me... Not sure if this is bug worthy. Can file if you like. 
    * "Set up goggles" link goes to new page - Works!

**Comment by secretrobotron** [comment]
More notes from Jonathan: https://docs.google.com/a/mozillafoundation.org/document/d/1qnikQF-U3vKKI72utGgYI_BM033upEAihWjLkOBh6iI/edit

**Comment by secretrobotron** [comment]
* Couldn't drag into my bookmark bar. Going to try this again on a Mac running Yosemite to see if that's the issue. I checked again with the older version and I could still do it there. 
* Had trouble with publishing.
* After the error I have to refresh the page. I’m still able to publish on the previous version. I’m unable to log in to my webmaker email on the test site, so I wonder if that has something to do with it?
* The setup ‘X-Ray Goggles’ link opens in the current page by default. Should it open in a new window?

**Comment by Pomax** [comment]
Couldn't drag into my bookmark bar: from where? From the landing page, or from the install page? (It won't work from the landing page, that button only activates the goggles)
