### ISSUE TITLE
Make a video for setting up and using x-ray goggles

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/goggles.webmaker.org#158]
Need to create a video for setting up and starting to use x-ray goggles as per https://redpen.io/tzd4ef140c28cc6090

- [x] come up with a script
- [x] ask Michelle if she can reach out to someone for us to record it
- [ ] film videos

**Comment by secretrobotron** [comment]
cc @xmatthewx

**Comment by secretrobotron** [comment]
Notes: https://etherpad.mozilla.org/supervideo

**Comment by secretrobotron** [comment]
Depends on #160

**Comment by secretrobotron** [comment]
Some info in #241 from @ldecoursy about an activity they're planning to do. Could be good to base the script off of it.

**Comment by secretrobotron** [comment]
New video url https://www.youtube.com/watch?v=XBjz-cpBT-8

**Comment by Pomax** [comment]
closing due to overhaul work.
