### ISSUE TITLE
Add analytics to goggles landing page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/goggles.webmaker.org#159]
Need to make sure there are proper analytics in x-ray goggles so we can track what users are doing.

**Comment by xmatthewx** [comment]
@adamlofting - if we can track anything more granular than pageview-to-publish, these are the likely actions:

 1. user arrives on Goggle's landing page
 2. might click Help link in page copy
 3. clicks "Activate Goggles" button on page
 4. clicks image element to edit with Goggles
 5. edits and clicks "update" in Goggles to change page
 6. clicks Publish in goggles to save the thing (Success!)
 7. might click Help or Exit in Goggles
 8. might click Setup Goggles link in page copy

https://redpen.io/rw825a9bece366d9ed

**Comment by adamlofting** [comment]
@secretrobotron, I dug up the history today and this was nearly solved by @admix last year: https://bugzilla.mozilla.org/show_bug.cgi?id=968291

Is there a dev who knows goggles who can work on finishing this? That will be quicker than me getting my head around goggles, but if not I can dig into the code.

**Comment by adamlofting** [comment]
We should also update to the latest version of webmaker-analytics (0.1.7) when we do this.

**Comment by xmatthewx** [comment]
@Pomax is making some revisions to goggles this week.

**Comment by secretrobotron** [comment]
@adamlofting no worries. @Pomax is certainly your man for this heartbeat, since he'll be putting together new goggles stuff anyway.

Can you guys work together to fix up what's not done yet?

**Comment by adamlofting** [comment]
@Pomax - was there enough context in this ticket, or would you like to talk through this as some point?

**Comment by Pomax** [comment]
can we do GA through goggles itself, since it's not "a webpage" and always runs on different domains?  I think once they're active, events don't go to the owning page anymore (i.e. clicking the image does not generate a click event on the image for the webpage to listen to, it gets cut off by goggles specifically to prevent the page from doing what it'd normally do).

**Comment by adamlofting** [comment]
Errrr...  :scream_cat:

I actually don't know enough about how Goggles works to answer that for sure. Could we test wiring up a single tracking event and running on staging?

It would be useful for our new onboarding measurement even if we only got data while goggles is used on the webmaker.org domain. But if it's not possible, we'll have to think about other data points to see how this works.

**Comment by secretrobotron** [comment]
:+1: let's do an experiment.
@Pomax think we can just add some GA events to webmaker.org/goggles for now? Like you said, goggles might get in the way, but maybe we can convince it not.. to?

**Comment by Pomax** [comment]
adding them to the landing page for "has this button been clicked?" etc. should be easy enough - this would be on the webmaker.org repo, in the angular controllers file (search for goggles in that and you should immediately find the goggles controller)

**Comment by secretrobotron** [comment]
- [ ] user arrives on Goggle's landing page
- [ ] might click Help link in page copy
- [ ] clicks "Activate Goggles" button on page
- [ ] clicks image element to edit with Goggles
- [ ] edits and clicks "update" in Goggles to change page
- [ ] clicks Publish in goggles to save the thing (Success!)
- [ ] might click Help or Exit in Goggles
- [ ] might click Setup Goggles link in page copy

**Comment by secretrobotron** [comment]
Easiest and most important step to take here is add some listeners/analytics on webmaker.org for the events checked off above.

Can follow up in another ticket to figure out in-goggles analytics functionality.
