### ISSUE TITLE
Simplify goggles editor modal

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/goggles.webmaker.org#160]
- [x] position and style window as specified in the image below
- [ ] keep "Basic" mode as default when editor opens
- [ ] move "Advanced" toggle to a small link in the corner
- [x] make it responsive (if possible)

![goggles_edit](https://cloud.githubusercontent.com/assets/53411/5911129/11ba0d4c-a590-11e4-9bcd-cd3f2692d193.png)

**Comment by xmatthewx** [comment]
![goggles_edit](https://cloud.githubusercontent.com/assets/53411/5911129/11ba0d4c-a590-11e4-9bcd-cd3f2692d193.png)

**Comment by xmatthewx** [comment]
This will resolve #147 
Designed in #152

**Comment by Pomax** [comment]
does the page that is being shown getting remixed already exist?

**Comment by secretrobotron** [comment]
I believe @xmatthewx just created the design in Sketch, but he can confirm. Probably have to whip this up in HTML from scratch.

**Comment by Pomax** [comment]
pending review in https://github.com/mozilla/goggles.webmaker.org/pull/165, basic/advanced switching has been ditched because "advanced" was already a basic look, and "basic" was more confusing than advanced...

**Comment by Pomax** [comment]
landed
