### ISSUE TITLE
Add help tooltips to goggles

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/goggles.webmaker.org#162]
- [x] Implement tooltip functionality as per the design below
- [x] Add "Tap text or images to edit" tooltip
- [x] Add "Tap quit to exit" tooltip

(@xmatthewx to follow up with images detailing the interactions)

**Comment by secretrobotron** [comment]
@xmatthewx can you detail how you want these tooltips to show up? What are the actions that trigger them?

**Comment by xmatthewx** [comment]
Both tooltips are intended for first-time use.

## Goggles Activated

![goggles_on](https://cloud.githubusercontent.com/assets/53411/5911055/48651004-a58f-11e4-9e41-c6d704e69f58.png)

## After user makes an edit

![after_edit](https://cloud.githubusercontent.com/assets/53411/5911056/48678172-a58f-11e4-8923-6afeffb10e31.png)

**Comment by Pomax** [comment]
This is pending review in https://github.com/mozilla/goggles.webmaker.org/pull/165

**Comment by Pomax** [comment]
add in https://github.com/mozilla/goggles.webmaker.org/pull/165

**Comment by Pomax** [comment]
landed
