### ISSUE TITLE
Prepare images for onboarding

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/goggles.webmaker.org#163]
Users will swap background images in onboarding activity. 
 - blur.jpg is heavily compressed and ok
 - shapes.jpg loses fidelity more quickly
 
https://www.dropbox.com/sh/186ynrtdyosyrmf/AACrfSmvJjAezOMkOC0v913Qa?lst

@cassiemc - What do you think hits the right balance of file size and crispness? Is %70 too much compression and too little quality? %80 seems definitely fine to me, but my eyes are now crossed staring at this.

**Comment by cassiemc** [comment]
I think 70% is fine on both. That said, the blur version is way less on-brand than the shapes. And the shapes should be have much more saturation. Did you try saving Shapes out as a png?

**Comment by xmatthewx** [comment]
Here's a [saturated version](https://redpen.io/qb248da8c506a457f7). 

As you said in an earlier round about a different image, I wonder if this competes too much with the  instructions and drowns out the site's banner for a first-time visitor. 

A PNG is about 4 times as many kb in this case. We need JPG for compression.

**Comment by cassiemc** [comment]
Ok. I do like the saturated, better. The top left corner is a big dark, perhaps, and the peach shades feel off-palette, but I think it's okay to go with now for testing.

**Comment by secretrobotron** [comment]
@xmatthewx @cassiemc ping! Should we swap out the images @Pomax is using on https://webmaker.mofostaging.net/en-US/goggles ?

**Comment by xmatthewx** [comment]
Oh dang, that's lookin' nice @Pomax! 

@secretrobotron I believe @Pomax used the latest images on [dropbox](https://www.dropbox.com/sh/186ynrtdyosyrmf/AACrfSmvJjAezOMkOC0v913Qa?lst). Should be good to go from my perspective.

**Comment by secretrobotron** [comment]
Excellent! I'll just close this then. Bloop! :bomb:

**Comment by secretrobotron** [comment]
:boom:
