### ISSUE TITLE
update goggles to login3

### ISSUE THREAD

**Issue by Pomax** [mozilla/goggles.webmaker.org#164]
While the main goggles webmaker nav was updated to login3, the publish dialog login system is still using the old approach, which means people cannot log in through the xray goggles publish dialog at the moment, needing to already somehow be logged in.

/cc @jbuck @cadecairos

**Comment by jbuck** [comment]
To clarify, only the front-end on /uproot-dialog.html is using login2 code.

**Comment by secretrobotron** [comment]
@Pomax should we try to push this into what we're shipping this week?

**Comment by Pomax** [comment]
I think that would be prudent, yes.
