### ISSUE TITLE
Background image should span full width

### ISSUE THREAD

**Issue by vazquez** [mozilla/goggles.webmaker.org#166]
Adding a `background-size: cover` and placing the image outside of the `.container` div should do the trick. 

Browsers tested: Firefox 37.0a2, Chrome 40, Safari 8.0.2

![screenshot 2015-01-30 10 00 43](https://cloud.githubusercontent.com/assets/1119821/5977545/fe8af72a-a866-11e4-8bf9-a02418182120.png)

**Comment by secretrobotron** [comment]
From QA in #153.

**Comment by Pomax** [comment]
one problem here is that we cannot move the image outside of the container, because of the highlighting needs wrt goggles. Moving it out means we'll be goggles-highlighting
```
<div>
  <div>
    <div>
     ...etc...
    </div>
  </div>
</div>
```
instead of 
```
<img src="/Shapes.jpg">
```

**Comment by vazquez** [comment]
Dang. Okay plan B, what about changing the background-color to be #00557d instead of white?

Warning: it might look horrible.

**Comment by Pomax** [comment]
https://github.com/Pomax/webmaker.org/commit/bebd9302e21f83137b7ff49a61f4347fbc7e474e should have this fixed now.

It also reveals the goggles UI needs some responsiveness in terms of how wide the editor box can be, because resizing hides the update/cancel buttons O_O!

**Comment by Pomax** [comment]
landed
