### ISSUE TITLE
Footer is not sticky

### ISSUE THREAD

**Issue by vazquez** [mozilla/goggles.webmaker.org#167]
Browsers tested: Firefox 37.0a2, Chrome 40, Safari 8.0.2

![screenshot 2015-01-30 10 03 40](https://cloud.githubusercontent.com/assets/1119821/5977608/510f705c-a867-11e4-8709-b5fc1082a156.png)

The footer does not sit at the bottom of the page.

**Comment by secretrobotron** [comment]
Apparently, this is not a problem unique to this page. Probably needs to be fixed in general.

**Comment by secretrobotron** [comment]
From QA in #153.

**Comment by Pomax** [comment]
This isn't a goggles issue, but a webmaker.org issue. The footer partial makes no attempts to be anchored to "further than the end of the page" if the page doesn't have enough content to fill the browser.

**Comment by Pomax** [comment]
I'm going to close this issue here, and file it as a concern over on webmaker.org... this is going to be affecting more pages if you make the browser big enough.
