### ISSUE TITLE
Text is too small on secondary content block

### ISSUE THREAD

**Issue by vazquez** [mozilla/goggles.webmaker.org#168]
Currently, the font-size on the secondary text block is 80%, this equals to 11px which is too small.

![screenshot 2015-01-30 10 05 06](https://cloud.githubusercontent.com/assets/1119821/5977671/ee85e424-a867-11e4-9f99-105715117da6.png)

Bumping it up to 90% or 95% should work nicely.

**Comment by secretrobotron** [comment]
From QA in #153.

**Comment by Pomax** [comment]
done in https://github.com/Pomax/webmaker.org/commit/01b5d8f16f7206c1427c4a178b77fe70ce438abb

**Comment by Pomax** [comment]
landed
