### ISSUE TITLE
Help icon is too hard to read

### ISSUE THREAD

**Issue by vazquez** [mozilla/goggles.webmaker.org#169]
Currently, the help icon looks like this:

![screenshot 2015-01-30 10 13 30](https://cloud.githubusercontent.com/assets/1119821/5977763/bb2a663a-a868-11e4-9957-f5316c879222.png)

I recommend removing the help text and increasing the size of the blue circle, as well as some additional modifications:

![screenshot 2015-01-30 10 13 18](https://cloud.githubusercontent.com/assets/1119821/5977777/d0dcc5fe-a868-11e4-8409-b188c4cec4fb.png)

This is what I did to get it to look like above:

![screenshot 2015-01-30 10 18 24](https://cloud.githubusercontent.com/assets/1119821/5977847/578a0436-a869-11e4-8724-19ccc513e1d0.png)

A note that the parent `li` element needs to be `position: relative`

**Comment by secretrobotron** [comment]
From QA in #153.

**Comment by Pomax** [comment]
I'd like to be a counterpoint here and note that removing "help" turns it into mystery meat: The letter "i" is not the most universally acknowledged symbol for help, why would it still make sense for that graphic to show more text as just an "i" in a circle?

**Comment by vazquez** [comment]
Cool :) keep the help text then.

On Friday, January 30, 2015, Mike Kamermans <notifications@github.com>
wrote:

> I'd like to be a counterpoint here and note that removing "help" turns it
> into mystery meat: The letter "i" is not the most universally acknowledged
> symbol for help, why would it still make sense for that graphic to show
> more text as just an "i" in a circle?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/goggles.webmaker.org/issues/169#issuecomment-72298985>
> .
>


-- 
Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez <http://twitter.com/iamrvazquez>
IRC: ricardo

**Comment by Pomax** [comment]
pinging @xmatthewx on this one

**Comment by xmatthewx** [comment]
I agree with everyone! Let's increase the font size, make it lowercase, and switch to a :question: : instead of :information_source:. You can use fa-question-circle if that's easier.

**Comment by Pomax** [comment]
@xmatthewx and then keep, or ditch, the word "help"?

**Comment by xmatthewx** [comment]
![screenshot 2015-02-04 10 33 09](https://cloud.githubusercontent.com/assets/53411/6043283/3afd3380-ac59-11e4-928a-27ec0481ebae.png)

**Comment by Pomax** [comment]
+1 I shall implementolate
