### ISSUE TITLE
Active X-Ray Goggle is misaligned with its bullet

### ISSUE THREAD

**Issue by vazquez** [mozilla/goggles.webmaker.org#170]
![screenshot 2015-01-30 10 19 58](https://cloud.githubusercontent.com/assets/1119821/5977888/96fe2f52-a869-11e4-8c8f-7394cf248478.png)

`margin-top: -1em` on the `button` element fixes the issue:

![screenshot 2015-01-30 10 21 13](https://cloud.githubusercontent.com/assets/1119821/5977898/bd8148c6-a869-11e4-9a13-d7da2c5fa97a.png)

**Comment by secretrobotron** [comment]
From QA in #153.

**Comment by Pomax** [comment]
Hmm, odd: I don't see that in my FF or Chrome. Can you confirm you still see this?

http://i.imgur.com/8gKl8jJ.png

**Comment by Pomax** [comment]
webmaker.org PR for the goggles pages landed, so closing this one (if it's still the case, let's file on webmaker.org instead)
