### ISSUE TITLE
Activate X-Ray Goggles has no hover or active state

### ISSUE THREAD

**Issue by vazquez** [mozilla/goggles.webmaker.org#171]
![screenshot 2015-01-30 10 21 13](https://cloud.githubusercontent.com/assets/1119821/5977944/099a8f24-a86a-11e4-9a35-62b4d8d0b2cb.png)

**Comment by secretrobotron** [comment]
From QA in #153.

**Comment by Pomax** [comment]
added in https://github.com/Pomax/webmaker.org/commit/f2b658fbdf1dfa2914e9ea089699fe905fb1582f and subsequent https://github.com/mozilla/webmaker.org/commit/a1766c06730e6b8ed41e21c5c5add5a2a4e3a8c3 (not sure why that became two commits)
