### ISSUE TITLE
Typo on headline

### ISSUE THREAD

**Issue by vazquez** [mozilla/goggles.webmaker.org#172]
![screenshot 2015-01-30 10 24 31](https://cloud.githubusercontent.com/assets/1119821/5977973/3a777dfa-a86a-11e4-8d83-42a4ab19b1ac.png)

It should say "Set up X-ray Goggles"

**Comment by secretrobotron** [comment]
From QA in #153.

**Comment by Pomax** [comment]
fixed in https://github.com/Pomax/webmaker.org/commit/79731ba4989eb102e08dd63b708ffcc2964f405a
