### ISSUE TITLE
Can't Publish If Not Signed In 

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/goggles.webmaker.org#185]
STR
1. Sign-out if you're signed in 
2. Go to https://webmaker.mofostaging.net/en-US/goggles
3. Activate X-Ray Goggles
4. Hit Publish button

Expected: Prompt for login or create an account
Actual: Page explodes (view screen shot for details) 

[screen shot 2015-02-09 at 1 40 06 pm](https://cloud.githubusercontent.com/assets/8070833/6113013/24c3fbdc-b062-11e4-94c5-8df4fffd4f2c.png)

**Comment by secretrobotron** [comment]
From #155.

**Comment by secretrobotron** [comment]
:boom:
