### ISSUE TITLE
can get in a state where mouse move doesn't highlight elements

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/goggles.webmaker.org#186]
STR:

1. navigate to https://webmaker.mofostaging.net/en-US/goggles
2. activate goggles
3. open an element for remixing, something big and close to the bottom is easier
4. click cancel in the remix dialog
5. before the cancel transition is done, get your mouse back on top of the element you were editing.
6. move it around but don't mouse out of this element and don't mouse over another.

Expected: the element should be highlighted
Actual: it still thinks I am in remix mode and won't let me highlight it until I mouse out of it or into another element.

**Comment by secretrobotron** [comment]
From #155.

**Comment by secretrobotron** [comment]
This is an existing goggles bug. Good to fix, but moving out of this milestone.

**Comment by Pomax** [comment]
given the migration of goggles soon, closing this so we can reopen it when people start hitting it again
