### ISSUE TITLE
Goggles click-jacks important elements on webmaker.org landing

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/goggles.webmaker.org#187]
1. Webmaker login buttons.
2. Help links

**Comment by Pomax** [comment]
when goggles is open, that is literally its job (nothing on-page should behave as "on page" element while the goggles are open). Functionality should however be restored once the goggles are closed again. Is this not happening? 

(STR?)

**Comment by secretrobotron** [comment]
Yeah, cool. This is how goggles has always been. Only a problem for the help text on the landing.
