### ISSUE TITLE
Undo/redo happens letter-by-letter instead of update-by-update

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/goggles.webmaker.org#188]
Try changing something with text in it on https://webmaker.mofostaging.net/en-US/goggles. Looks like goggles treats each preview as an undo/redo state.

Would be ideal to just remember states after "update" is clicked.

**Comment by Pomax** [comment]
we can probably fix this by passing an `ignoreState` or some such when posting the update message, and have the state recorder not do a history.push if it exists.

https://github.com/mozilla/goggles.webmaker.org/blob/master/public/easy-remix-dialog.js#L225 trigges the update on each letter typed, https://github.com/mozilla/goggles.webmaker.org/blob/master/webxray/src/mix-master.js#L207 then does the updating, which lives in https://github.com/mozilla/goggles.webmaker.org/blob/master/webxray/src/mix-master.js#L130 which in turn calls https://github.com/mozilla/goggles.webmaker.org/blob/master/webxray/src/mix-master.js#L61 which relies on commandManager.run, which lives over in https://github.com/mozilla/goggles.webmaker.org/blob/master/webxray/src/command-manager.js#L37 and has the **actual** code that does the stack pushing.

We could change https://github.com/mozilla/goggles.webmaker.org/blob/master/webxray/src/command-manager.js#L38 to be something like
```
var command = createCommand(name, options);
if(!options.ignoreState) {
  undoStack.push(command);
  redoStack.splice(0);
}
command.execute();
```

**Comment by secretrobotron** [comment]
@Pomax thanks a bunch for the tips. Was helpful to navigate the code.

I had to do something that was a bit more of a hack because of the way goggles replaces entire elements and only remembers the last element it's supposed to affect.
