### ISSUE TITLE
Add analytics to goggles tool

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/goggles.webmaker.org#191]
Stemming from #159, we should add some analytics to goggles if possible.
- [ ] clicks image element to edit with Goggles
- [ ] edits and clicks "update" in Goggles to change page
- [ ] clicks Publish in goggles to save the thing (Success!)
- [ ] might click Help or Exit in Goggles

**Comment by Pomax** [comment]
closing due to overhaul work.
