### ISSUE TITLE
Publish dialog breaks in Safari

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/goggles.webmaker.org#193]
Visit goggles.webmaker.org. Try to publish. Dialog will show up, but never display its message. This is in the console:
```
[Error] ReferenceError: Can't find variable: WebmakerLogin
	(anonymous function) (auth-login.js, line 16)
	execCb (require.js, line 1635)
	check (require.js, line 871)
	enable (require.js, line 1142)
	init (require.js, line 779)
	(anonymous function) (require.js, line 1412)
```

**Comment by Pomax** [comment]
When did we decide to support Safari?

**Comment by secretrobotron** [comment]
Most of the features appear to work. Just not publishing, so might just be an auth problem. @jbuck @cadecairos any insight?

(Is there a support matrix somewhere?)

**Comment by Pomax** [comment]
closing due to overhaul work.
