### ISSUE TITLE
Make install more prominent

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/goggles.webmaker.org#195]
Suggestion that we make the link to install goggles more prominent on the site, based on two key reasons.

1. Ultimately people need to install the tool to continue using it - the link should be larger or bold so people don't miss this (whether they follow the three steps for their first remix or not).
2. We learned some existing curricular resources note to install the X Ray Goggles by visiting https://webmaker.org/goggles

**Comment by Pomax** [comment]
closing due to migration/overhaul work.
