### ISSUE TITLE
User feedback on responsiveness and resources

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/goggles.webmaker.org#198]
From the webmaker list:

> Hi all,

> I just want to share my opinion, which I felt on X-Ray Goggles tool!!

> I think the X-Ray Goggles, need a very good Internet speed to work normally and I guess it even putting load on RAM?[may be, not sure on RAM] and Appmaker also need Internet with good speed to get loaded completely!!!

> Can we try come-up with light weight and which can open with average or a little below average Internet? and this is purley my opinion which I felt and it may be wrong[I might have mistaken :) ]

**Comment by Pomax** [comment]
closing for now - good feedback but it can't be turned into anything actionable at this point in time.
