### ISSUE TITLE
Goggles Makes Can't Be Edited After Publishing 

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/goggles.webmaker.org#200]
For all other makes (popcorn, thimble etc.) you can edit a make after publishing without having to remix the page by going to webmaker.org/me (when you're logged in). However with the new goggles makes you cannot edit them after they have been published. 

STR: 
1. login to webmaker.org
2. go to webmaker.org/me
3. Hover your cursor over the Goggles make you want to edit 
Expected Result:  a pencil appears that you can click to edit that make
Actual: No pencil appears

See visual here: http://discourse.webmaker.org/t/x-ray-goggles-question/1277/3

cc. @secretrobotron @cadecairos

**Comment by LucyeoH** [comment]
Please add labels: bug + help report

**Comment by Pomax** [comment]
This is by design - Goggles remixes are a one time make, without the possibility of in-tool further editing like Popcorn or Thimble
