### ISSUE TITLE
Can't publish on Safari v8.0.5

### ISSUE THREAD

**Issue by hannahkane** [mozilla/goggles.webmaker.org#209]
safari 8.0.5 

STR:

Click Publish -> get Login prompt -> land on id. for login -> get "You've logged in. You can close this window" message -> Close window -> login prompt is still there, rather than the Publish prompt

**Comment by Pomax** [comment]
Can you check the developer tools in Safari while this happens? The login status gets tracked via `localStorage`, so we should be able to see if values are getting saved or not.

When you get to the `login-confirmation.html` page after signing in, and on that page you open the developer tools, then go to the "console" and type `localStorage`, what is the object result?

On firefox, for instance, it shows this prior to login:
```
Storage { goggles-publish-data: "{"html":"<!DOCTYPE html><html><head…", length: 1 }
```
But once the login succeeds, it shows this:
```
Storage { goggles-publish-data: "{"html":"<!DOCTYPE html><html><head…", goggles-auth-token: "abcd1234…", length: 2 }
```

**Comment by Pomax** [comment]
this works now.

**Comment by hannahkane** [comment]
Hmm..trying this in Safari now, and can't get to the login screen. When I click "Sign In" it very quickly opens a new tab for id.webmaker, but then immediately closes it. No errors logged.

**Comment by Pomax** [comment]
can you check whether your bookmarklet is for the `https` page? I've seen it do this if the library is for the `http` version (without the **s** at the end), wondering if you're running into that.

**Comment by Pomax** [comment]
Hmm, there's some odd things going on in Safari that don't happen in Firefox, Chrome, or IE, which will require some more investigating...

**Comment by hannahkane** [comment]
Works for me in Safari 8.0.5 now!

**Comment by Pomax** [comment]
awesome
