### ISSUE TITLE
tell users where to report bugs

### ISSUE THREAD

**Issue by Pomax** [mozilla/goggles.webmaker.org#217]
Currently there is no link to this issue tracker for reporting bugs, which would be useful if we want reports from the more technical users.

**Comment by Pomax** [comment]
Some options:

- UI button that says "report bug" that you click and just opens https://github.com/mozilla/goggles.webmaker.org/issues/new
- Quick link to the home page (although the homepage is not structured to easily find where to go if you found a bug)
- ...?

**Comment by Pomax** [comment]
good suggestion: change the meaning of the "help" button so that it opens an iframe similar to the publish button, with a document that is a little more helpful than the keyboard shortcuts are now. If we like that idea @hannahkane we can make do some comps for a "help landing" page that can be accessed through the library as well as from the "homepage" /cc @kristinashu

**Comment by hannahkane** [comment]
I like this idea. If we do an FAQ on this help landing page, maybe we kill the [related ticket about the SUMO page](https://github.com/mozilla/teach.mozilla.org/issues/1336). 

Help landing page might include:
 * A few basic FAQs (the ones we already have [here](https://support.mozilla.org/en-US/products/webmaker/x-ray-goggles + maybe something about supported devices + maybe something about "How to use X-Ray Goggles to teach others about the Web")
 * How to report a bug
 * A relevant discourse thread
 * @mozteach 
 * teachtheweb@mozillafoundation.org

Can anyone think of anything else to include?

**Comment by Pomax** [comment]
teach IRC channel?

**Comment by kristinashu** [comment]
Could we also link to the FTU activity page?

**Comment by Pomax** [comment]
if that's where we tell them how to file bugs they find, :+1:

**Comment by hannahkane** [comment]
This is a good list. Will open up a new ticket to design the page.

**Comment by hannahkane** [comment]
See #228. Closing this ticket.
