### ISSUE TITLE
Finalize goggle teaching activities on install page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#218]
Finalize the three activities that appear at the bottom of the landing page: https://redpen.io/p/wjdd96d46ae8c63dc3

Currently:
[Hack the News] (http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session02-hackthenews.html), [Hacking My Media] (https://stephguthrie.makes.org/thimble/ODU3ODAxMjE2/hacking-my-media-with-x-ray-goggles), and [Hack Great Science for Girls] (http://www.lessonpaths.com/learn/i/diving-in/hack-great-science-for-girls-with-the-xray-goggles)

Once we know which activities we'll need the intro copy and images.

**Comment by hannahkane** [comment]
I'd say we could plan to have these be relatively static, since we often frame Goggles as our "gateway" tool - something to introduce basic concepts and get people excited to learn more via Webmaker and Thimble. But this is a good question for @chadsansing since I'm not sure how much Goggles fits into his curriculum roadmap.

**Comment by chadsansing** [comment]
@hannahkane, @pomax: I would say static for now; not sure how much Goggles content we will produce in the near term, so it may be enough just to change one activity for another by hand later on; make sense?

**Comment by Pomax** [comment]
if it's low frequency, static content is perfectly fine.

**Comment by chadsansing** [comment]
<low speaking voice>It will be low-frequency.</low speaking voice.>

**Comment by kristinashu** [comment]
I've pulled intro copy from the individual activity pages so @Pomax can replace the placeholder copy on http://ecks-rey-giggles-are-landing.herokuapp.com/

@hannahkane or @chadsansing does this copy work for you? Site will look best if the three intro paragraphs are similar in length :)

**Hack the News**
Intro text: Learners will use X-Ray Goggles to remix a news website, learning about openly-licensed resources, different forms of media, and how to create something new on the Web through remix.
CTA: Try this activity (with fontawesome Arrow)
link: http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session02-hackthenews.html

**Hacking My Media**
Intro text: The goal of this activity is for participants to think critically about their identities and the media they enjoy. They will use these reflections to create their first webpage by hacking and tinkering with an existing webpage.
CTA: Try this activity (with fontawesome Arrow)
link: https://stephguthrie.makes.org/thimble/ODU3ODAxMjE2/hacking-my-media-with-x-ray-goggles

**Hack Great Science for Girls** 
Intro text: The goal of this hacktivity is for participants to create their first webpage by hacking and tinkering with an existing webpage.
CTA: Try this activity (with fontawesome Arrow)
link: http://www.lessonpaths.com/learn/i/diving-in/hack-great-science-for-girls-with-the-xray-goggles

Images are all here: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLX1BHbG1CQ1B3Zkk&usp=sharing

**Comment by hannahkane** [comment]
wfm. Thanks, @kristinashu.

**Comment by chadsansing** [comment]
Likewise.

**Comment by Pomax** [comment]
copy, links, and images updated
