### ISSUE TITLE
Add instructions on how to view bookmark bar to install page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#223]
If a user's bookmark bar is not showing, the user might not know how to make it visible so we should add instructions on how to view bookmark bar. Will need to detect which browser the user is in then link to 'view bookmark bar' instructions for that browser.

**Comment by kristinashu** [comment]
Maybe we can just link to sumo https://support.mozilla.org/en-US/kb/install-x-ray-goggles#w_enable-your-bookmarks-toolbar

<img width="1193" alt="screen shot 2015-10-28 at 1 40 25 pm" src="https://cloud.githubusercontent.com/assets/1068783/10802319/8596403e-7d79-11e5-8f58-7ec3c9a4d1e1.png">

**Comment by hannahkane** [comment]
+1 to sumo link idea

**Comment by Pomax** [comment]
Sumo only covers mozilla's product, though. The Goggles will run in any HMLT5 browser, so it might be worth finding some universal "how do I put things in the bookmark bar?" page?

**Comment by hannahkane** [comment]
The Sumo question @kristinashu referenced to includes links to instructions for other browsers. I think it could work.

**Comment by Pomax** [comment]
oh wow I completely missed that. I retract my earlier statement!

**Comment by Pomax** [comment]
added
