### ISSUE TITLE
Copy updates

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#224]
Going to start a running list of copy changes that come up:

Use 'publish' and not 'save' and update button to Create an account':
<img width="800" alt="screen shot 2015-10-20 at 1 13 16 pm" src="https://cloud.githubusercontent.com/assets/1068783/10619774/69f1d968-772c-11e5-9cd5-cada4e97a025.png">

**Comment by Pomax** [comment]
you mean turn the word "save" in the paragraph text to "publish"? The last bit may have been cut off, I'm assuming you meant to change the "Sign Up" button so that it reads "Create an Account"?

**Comment by kristinashu** [comment]
Yeah, that's right. It's taken from conversations here https://redpen.io/p/wjdd96d46ae8c63dc3

But I'm also not even sure if 'remix it again' is the right copy? I think you and @hannahkane where talking about that in IRC?

**Comment by hannahkane** [comment]
Don't recall talking about "remix it again" recently, but it does seem superfluous. First line could be "Sign In or Create an Account". Second could be simply, "Once you have an account, you can publish your remix and share it with friends." Buttons could read "Sign in" and "Create an account".

**Comment by kristinashu** [comment]
Perfect!

**Comment by Pomax** [comment]
Updated texts:

![screenshot 68](https://cloud.githubusercontent.com/assets/177243/10623975/fe6afaa4-7748-11e5-9685-998896ca1f05.png)

**Comment by kristinashu** [comment]
Closing. We can open new tickets if anything else comes up.
