### ISSUE TITLE
User testing and/or input from goggle users

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#226]
Based on comps from https://github.com/mozilla/teach.mozilla.org/issues/1310

Find 5-7 users to walk through comps with and get their thoughts. Users should be mix of teachers and students.

**Comment by Pomax** [comment]
@hannahkane why would be the best person to drive this, or who can we add to this bug to make sure we can follow up on this relatively short-term?

**Comment by hannahkane** [comment]
@kristinashu - would you be able to walk through with a couple people in the YVR office, preferably people who aren't super familiar with Goggles?

I can try to do it with the newly forming Hive Cascadia group here in Portland.

**Comment by kristinashu** [comment]
Yeah, sounds good. I'll work on making more thorough Invision comps and some questions to ask users.

**Comment by kristinashu** [comment]
Here are my suggested steps for walking through the comps. I say 'Reality' to represent what the real site would be like and 'Test' for the constraints because we're using comps. When I say 'Go through step' step I mean the user should be able to read the comp and know what to do.

1) Start and read http://ecks-rey-giggles-are-landing.herokuapp.com/
2) Reality: Click on “Sample activity page” - Test: go to comps https://invis.io/7J4O5KXNT
3) Go through step (choose 'Get started')
4) Reality: Click on X-Ray Goggles in bookmark bar - Test: Click on box to go to next screen
5) Go through step (click on title)
6) Reality: Delete, type text and click update - Test: Click update
7) Go through step (click on top image)
8) Reality: Delete, type text and click update - Test: Click update
9) Go through step (click on middle image)
10) Reality: Delete, type text and click update - Test: Click update
11) Go through step but want to skip (click ‘Skip this step')
12) Go through step (click ‘Publish’) - finished

Purpose is to see where users get stuck and when they have questions or would want more info. Would be nice to then see if the users could then go to a random site, activate goggles and remix the page.

Let me know what you think @cassiemc @hannahkane @Pomax

**Comment by kristinashu** [comment]
I'm thinking that if we're confident with this general direction, we should build it out and then do some user testing and tweak the tutorial as needed. I don't think testing this type of project with comps will be realistic enough to get good feedback. Thoughts?

**Comment by cassiemc** [comment]
Agree with @kristinashu, if we're confident in one direction let's move on that then tweak as necessary. It doesn't hurt to test with comps for basic impressions but with more complex scenarios the script would need to read really human, and this might be better to just walk through with a couple people in person.

**Comment by hannahkane** [comment]
wfm

**Comment by Pomax** [comment]
Yeah for in-person asking people to run through this, these steps sound pretty good.

**Comment by kristinashu** [comment]
@Pomax has been super quick at making the FTU site so I think we'll be able to test it with users at MozFest! 

@hannahkane @cassiemc how would we go about doing this? Can we set up a table or something?

**Comment by cassiemc** [comment]
Not sure what the best occasion is for this. How to add sessions... or if the Science Fair is the best place. @Saallen if we wanted to set up a user testing session how/where/when is the best time and place?

**Comment by hannahkane** [comment]
@Saallen - would this be a mis-use of the Help Desk Hub? I signed up for a Saturday 12pm timeslot to offer help on "How to contribute via design and engineering." Maybe we could run some user tests as part of that?

**Comment by kristinashu** [comment]
Closing and focusing on testing at MozFest #235
