### ISSUE TITLE
Design a Help landing page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/goggles.webmaker.org#228]
Content:

 * A few basic FAQs (the ones we already have [here](https://support.mozilla.org/en-US/products/webmaker/x-ray-goggles + maybe something about supported devices + maybe something about "How to use X-Ray Goggles to teach others about the Web")
 * How to report a bug
 * A relevant discourse thread
 * @mozteach 
 * teachtheweb@mozillafoundation.org
 * teach IRC channel
 * link to FTU activity

**Comment by kristinashu** [comment]
I'm thinking we just link to the FAQs. 
![help 2x](https://cloud.githubusercontent.com/assets/1068783/10744532/d81cd56c-7bf7-11e5-8dfb-00603fed78ca.jpg)

It's ok to get rid of the list of keyboard short cut keys? I'm interested to know how many users actually use them. Seems like something only advanced computer users would use.

cc @Pomax @hannahkane

**Comment by hannahkane** [comment]
Nice. :) Agree that linking to FAQs makes sense.

Copy suggestion: "Having trouble? No problem! We have several ways for you to get help."

**Comment by kristinashu** [comment]
Haha! Yes, it definitely shouldn't say "for you to help you"

![ftu 2x_help](https://cloud.githubusercontent.com/assets/1068783/10745375/74387374-7bfe-11e5-99bd-0d17ac0bf3d5.jpg)

**Comment by hannahkane** [comment]
It was very user-empowering. :)

**Comment by kristinashu** [comment]
Closing and opened implementation ticket https://github.com/mozilla/goggles.webmaker.org/issues/231
