### ISSUE TITLE
implement the FTU page

### ISSUE THREAD

**Issue by Pomax** [mozilla/goggles.webmaker.org#229]
based on https://github.com/mozilla/goggles.webmaker.org/issues/230, comps on https://invis.io/F44O6ZJGY

**Comment by Pomax** [comment]
Additional note: this is essentially the same template as the homepage, but with different main content (preserving the userbar and footer)

**Comment by kristinashu** [comment]
@Pomax here are the animal images https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLV3JwR1loQlVTYlU&usp=sharing
I'll probably be updating them but they'll work as placeholders for now. Is there a way to do retina images without the user seeing the @2x in goggles? I think we need retina but might get confusing for the user if they have to type it in.

**Comment by Pomax** [comment]
I don't think we can get away with that, since that's how the browser deals with it. We CAN, however, just use the retina version and set the width manually so it looks good on retine, with an irrelevant downscale on regular screens.

**Comment by kristinashu** [comment]
Perfect!

**Comment by Pomax** [comment]
First draft is now up on https://ecks-rey-giggles-are-landing.herokuapp.com/ftu, although due to changed to the goggles (mostly making it generate some more events for us to tap into) it will only work with the goggles as bookmarked from https://ecks-rey-giggles-are-landing.herokuapp.com.

This is still missing the initial start with the overlay that lets you pick whether to just muck about or run through the tutorial.

**Comment by humphd** [comment]
For https://ecks-rey-giggles-are-landing.herokuapp.com/ftu:

* The blue "Active the X-Ray Goggles" popup isn't clearly set off from the other content.  I wonder if you lightly grayed out the rest of the page beneath, or animated this popup slightly, if it would help draw the user's eye to it.  I wasn't sure where to look when the page loaded, since everything has the same visual weight on load.
* "Clickon" should be "Click on"
* "X-Ray Goggles in your bookmark toolbar to activate the Goggles." make that a link so that if I don't have the bookmark for some reason, I can go get it.  There's a "help" link at the bottom, but I think it comes too late to be useful.

For https://ecks-rey-giggles-are-landing.herokuapp.com:

* I wonder if you should add an animated gif to this page, showing how one drags the bookmark to the toolbar.  I did a bunch of these for Thimble using http://www.cockos.com/licecap/

This is really coming along nicely, great work.

**Comment by Pomax** [comment]
This is still a draft, so have a look at https://invis.io/F44O6ZJGY and see if that addresses some of the issues (copy is still rough draft too, mostly concerned getting the major lines implemented before calling it a day today).

As for animated gifs: I would strongly ask we don't, at least not on the main site. We got some lovely feedback from people who use goggles that the graphic we have now is perfect, so I'd rather keep it that way unless the rest of the world, once we push to prod, says it's not.

**Comment by Pomax** [comment]
User feedback: "the first edit bubble tells me to play with the various sections, but I can't do that because after the first edit the next bubble tells me to change text. I don't want to change text yet, I want to keep playing with the animals". 

Which is an interesting problem because the only way for us to detect whether someone's done mixing up the animals is to have that step have an "okay I am done, what do I do now?" button.

**Comment by kristinashu** [comment]
@Pomax I guess the user could go 'back'. Maybe we could be more playful and add a link of text that's like - hey I'm not done mixing up my animal, bring me back. 

Also, are you able to make it like the old example http://mozilla.github.io/goggles.webmaker.org/Awesome%20Animal%20Builder%20-%20Large%20Animals.htm where users can rename the three animal sections at once? I think once users can do that it'll they'll play around with it more before saving.

**Comment by mmmavis** [comment]
some QA feedback

<img width="467" alt="screen shot 2015-10-28 at 10 10 44 am" src="https://cloud.githubusercontent.com/assets/2896608/10796623/35387c6e-7d5c-11e5-9a9f-df7b42a6d931.png">

add more space to the top of the modal so people can read the paragraph :wink:

**Comment by Pomax** [comment]
as a counter point though: people have the option to run this page either with goggles, in which case you get this dialog, or without goggles entirely (comp 1 on invision), so if you elect to do this with goggles, you really need to launch the goggles. Hiding some text to be "inconvenient" feels like given the user's choice the blocking shouldn't be a problem.

**Comment by kristinashu** [comment]
That paragraph text is also the same as on the pre cursor to this page so they should have read it by the time they get to that screen https://invis.io/CN4PZ49ZA

@Pomax re: blue esc notification. Yeah it's redundant. We say it in the bubble and also in the bottom right corner (where it says want you're hovering over) and there's the actual quit/esc button in the goggles UI.

**Comment by Pomax** [comment]
I always forget that corner text is there... I wonder if we can somehow test it's efficacy, it feels like it might just be taking up a bit of screen real estate rather than contribute to a user's ability to goggle all the things.

**Comment by kristinashu** [comment]
I'd say 90% of what it says is useless and it's also not very visible right now so I doubt people use it. But we definitely need to get some feedback from users. Trying to set something up for Mozfest.

**Comment by Pomax** [comment]
nice!
