### ISSUE TITLE
Finialize FTU walkthrough

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#230]
Based on https://github.com/mozilla/teach.mozilla.org/issues/1310 and https://github.com/mozilla/teach.mozilla.org/issues/1324

Comps in progress are here https://invis.io/F44O6ZJGY

Need to finalize copy and illustrations.

**Comment by kristinashu** [comment]
Here are the updated comps: https://invis.io/F44O6ZJGY

I've grouped the edits so clicking the image section now shows all the images in one editor. This way the tutorial has fewer fixed steps and is easier for users to play around with the image names.

@hannahkane is there anyone who could help with copy? Might be nice to get outside eyes on it to make sure everything is clear. Also think we could have some fun with the copy to make it a little more playful.

I like @cassiemc comment in invision about making the bubbles move a little - like in invision. @Pomax you up for that?

Also started to play around with the illustrations - using a fox, dinosaur, and (thunder)bird. @cassiemc let me know if you're good with this general direction and then I'll start fine turning them.

<img width="789" alt="screen shot 2015-10-26 at 1 29 17 pm" src="https://cloud.githubusercontent.com/assets/1068783/10741777/a900b1ce-7be6-11e5-8f13-e94a69b9da49.png">

**Comment by cassiemc** [comment]
Love it! My only suggestion might be a little more rock n roll in each panel. It's very kid-like at the moment, which might be the point. Love the icecream cone and sunglasses. Maybe something on the fox head instead of a flower? the shadows around the dino arm and chin feel a little different than the wing shadows of the bird, but in general these go together quite well. Could also consider darker colors or patterns to minimize the pastel effect.

**Comment by hannahkane** [comment]
Those animals are adorbs. :)

I think all of our copywriters are pretty consumed with MozFest right now. I've added some suggested copy below. Maybe @KevZawacki or @ldecoursy could take a look after the next round.

01.
Headline: Tutorial
Learn about the remixing superpowers of X-Ray Goggles by playing a mix-and-match animal game.

If you haven't installed X-Ray Goggles yet, click here to install.

02.
Headline: Activate X-Ray Goggles
To begin the game, activate Goggles by clicking on X-Ray Goggles in your bookmark bar.
(By the way, you can activate Goggles on any website. To deactivate, just press 'esc' on your keyboard at any time.)

03.
Headline: Remix the Words
Hover over this section of text to highlight it, and then click to open the editor.

04.
Headline: Introduce Your Animal Friend
Delete the text between <h1> and </h1> and give your animal a name. Then, update the text between <body> and </body> with some details about your animal. Where does it live? What does it eat? What kind of music does it like?

Click the Update button to save your changes.

05.
Headline: Remix the Images
Hover over the animal sections to highlight, and then click to open the editor.

06.
Headline: Make a New Animal!
Play around by swapping the words dinosaur, fox, and bird in each section.

Click the Update button to save your changes.

07.
Headline: Publish Your Animal
You're done! When you're ready to publish and share your animal, click on Publish.

**Comment by kristinashu** [comment]
Thanks for the feedback and copy. I still need to work on the illustrations but here are comps with the new copy https://invis.io/F44O6ZJGY

**Comment by hannahkane** [comment]
Awesome. @ldecoursy - if you have time, could you take a look at Kristina's comps and comment on copy specifically?

**Comment by ldecoursy** [comment]
This looks good and fun! My suggested edits and q's below.

01. Question - do you click to install or can you drag the button to the bookmarks toolbar?
02. Click on X-Ray Goggles in your bookmark toolbar to activate Goggles on any website. To deactivate, just press 'esc' on your keyboard at any time. 
04: Headline: 
05. Hover over each of the animal sections (head, body, legs) to highlight, then click to open the editor.
06. Question/suggestion - should we add a note that says you can also add images from the web? I wonder if people understand you can't just type random words in there for different animals to appear. 

I might also suggest switching the order of the steps- so remix the images first then give the animal a name and description.  

Suggested edits to the tutorial description:
This tutorial walks you through a mix-and-match game to learn about the key features of X-Ray Goggles. With the X-Ray Goggles activated, you can change the text and switch out the different dinosaur, fox and bird sections to create a new web page featuring your own animal friend.

**Comment by hannahkane** [comment]
+1 to all of @ldecoursy's copy and ordering suggestions.

For Lainie's fourth item, I think a parenthetical could be informative, without distracting from the task at hand. Maybe: "(When using Goggles, you can add any image from anywhere on the Web. Be sure to respect copyright law!)" 

I believe clicking on the button on page 1 sends you to the Install page, where you drag to the bookmark bar. Could we put the bookmarklet right there in the tutorial, @Pomax?

**Comment by kristinashu** [comment]
Thank you @ldecoursy for the copy! I think switch the order around to edit the image then text is a great idea.

**Comment by kristinashu** [comment]
I'm not sure if we should have the install on this FTU page. Might be better to drive people to the install page so they get the overview and see some of the other content on the install page.

**Comment by Pomax** [comment]
Clicking on the button just activates the goggles, you have to drag them into the bookmark bar for them to become "installed". We can't change that behaviour, since the bookmark is built off of the link element users need to drag. Since the bookmarklet should activate the goggles, the link has to always activate the goggles.

I'd say keep "install" in one place, and direct people there if they haven't installed it yet. It's both easier to maintain and prevents people from trying to "find" the right place, since there's only one, and it's on the landing page.

**Comment by hannahkane** [comment]
wfm

**Comment by kristinashu** [comment]
Walkthrough is done. Opening new ticket to finalize animal illustrations #232
