### ISSUE TITLE
Implement help page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#231]
Based on design in #228 

![ftu 2x_help](https://cloud.githubusercontent.com/assets/1068783/10766307/303aaf70-7c94-11e5-9eb3-7edfc4884ee9.jpg)

**Comment by Pomax** [comment]
Implemented, live on  https://x-ray-goggles-staging.herokuapp.com -> click "drag" button -> click "help"

![screenshot 33](https://cloud.githubusercontent.com/assets/177243/10896989/4ec16d66-8172-11e5-8960-35f27a6082f3.png)

**Comment by kristinashu** [comment]
Looks good!

**Comment by hannahkane** [comment]
Pretty!

**Comment by Pomax** [comment]
no bad links after testing: closing.
