### ISSUE TITLE
Finish animal illlustrations for FTU

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#232]
Based on Finalize FTU walkthrough #230 

Illustrations going into there FTU comps https://invis.io/F44O6ZJGY

Getting close but still working on them:
<img width="800" alt="screen shot 2015-10-27 at 12 41 01 pm" src="https://cloud.githubusercontent.com/assets/1068783/10770345/07af92f0-7ca8-11e5-84ef-44a62fd205ed.png">

**Comment by cassiemc** [comment]
Yeeeeeah I like these @kristinashu

**Comment by kristinashu** [comment]
@cassiemc great! I made some little updated. Let me know if you have any feedback.

![animals_fox top](https://cloud.githubusercontent.com/assets/1068783/10801485/cc1f1de6-7d74-11e5-84e9-74e03b105354.jpg)

**Comment by cassiemc** [comment]
Very fun @kristinashu :D

**Comment by kristinashu** [comment]
Sweet! Closing.

**Comment by edrushka** [comment]
cc-ing @HPaulJohnson @KevZawacki @valianttry to ensure they see these awesome images. Maybe we could use these (the fox specifically) on social or as a static snippet icon.
