### ISSUE TITLE
Decide what FTU page looks like on mobile

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#234]
Guessing nothing will work so what should this page look like/say?

**Comment by hannahkane** [comment]
Any reason not to include the same warning as the install page?

**Comment by kristinashu** [comment]
On the install page users can still read about goggles on mobile so even though they can't install them they get something out of it. But the activity is really dependent on accessing goggles and they would get stuck on mobile. Also, the landing screen for FTU has a popup already so seems messy to have two.

Here are I few versions, I think the third version is working best but let me know what you think.

![mobile 2x-1](https://cloud.githubusercontent.com/assets/1068783/10859670/fb68a050-7f1c-11e5-805e-98bec24b5313.jpg)
![mobile 2x-2](https://cloud.githubusercontent.com/assets/1068783/10859669/fb68817e-7f1c-11e5-9a29-8842cf492b6f.jpg)
![mobile 2x-3](https://cloud.githubusercontent.com/assets/1068783/10859671/fb68f532-7f1c-11e5-9a95-2d8728f9e120.jpg)

**Comment by kristinashu** [comment]
Closing v2 or v3 would just show the page and not activate any of the bubble steps.

**Comment by hannahkane** [comment]
Agree that the third one is best. It's friendly, but conveys the message clearly.

I'd suggest much shorter copy on the page though. This much copy kind of makes your eyes glaze over and not want to read it, and it's really important that they do. I don't think we need to explain what the activity is; we just need to say that it doesn't work in mobile. Maybe @KevZawacki can help come up with something clever.

**Comment by KevZawacki** [comment]
@hannahkane Agreed that shorter is better. Maybe:

Header: X-Ray Goggles Aren't Meant for Mobile

Copy: Currently, only desktop users have x-ray vision superpowers. To get started using X-Ray Goggles, try this activity on your desktop browser.

**Comment by kristinashu** [comment]
Million times better! Thanks @KevZawacki 

![mobile 2x-4](https://cloud.githubusercontent.com/assets/1068783/10896406/beadbb92-816e-11e5-97fb-57e1cf9b4923.jpg)
