### ISSUE TITLE
User test at MozFest

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#235]
Based on - User testing and/or input from goggle users #226 

We're going to do user testing during MozFest. On Saturday at 12pm we'll use @hannahkane 's Help Desk Hub slot - "How to contribute via design and engineering."

Would be best to test users who are already familiar with goggles and also users who aren't familiar with goggles.

Steps would be:
1) Read http://ecks-rey-giggles-are-landing.herokuapp.com/
2) Install X-Ray Goggles
2) Click on “Sample activity page” to go to https://ecks-rey-giggles-are-landing.herokuapp.com/ftu
3) Do entire FTU activity:
- Get started
- activate X-Ray Goggles by clicking in bookmark bar
- click on image, edit and update
- click on title, edit and update
- click on paragraph, edit and update
- publish (by signing up)

Follow up questions:
- do/would you use short cut keys?
- in the goggles UI, is the bottom right text useful?

Goal: Get user feedback and see where they get stuck or are confused - determine the best way to clarify.

cc @Pomax @cassiemc @flukeout

**Comment by hannahkane** [comment]
This looks good to me. I think we'll be able to learn a lot during this time. Thanks, @kristinashu!

**Comment by kristinashu** [comment]
Coolio, closing.
