### ISSUE TITLE
Styling of FTU activity 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#238]
Looking awesome @Pomax just a few styling things:

First box needs some padding at the bottom (between 'Skip tutorial' and bottom of white box). Might be a mac thing because it looked good during your demo.

Dev:
<img width="781" alt="screen shot 2015-10-30 at 10 41 17 am" src="https://cloud.githubusercontent.com/assets/1068783/10853452/56403aee-7ef3-11e5-8d8f-5d2d1c5c2e2a.png">

Comp:
<img width="873" alt="screen shot 2015-10-30 at 10 49 36 am" src="https://cloud.githubusercontent.com/assets/1068783/10853620/4052bf8a-7ef4-11e5-9707-49d387e49f83.png">

All the bubbles need:
- little arrow pointer 
- should all be 400px wide
- links (back and skip) look small and should be aligned with the paragraph text
- too much padding at the top and not enough at the bottom (again maybe a mac thing?) 

Dev:
<img width="588" alt="screen shot 2015-10-30 at 10 41 24 am" src="https://cloud.githubusercontent.com/assets/1068783/10853453/56409f0c-7ef3-11e5-82ad-bdf3d652b7cd.png">
<img width="894" alt="screen shot 2015-10-30 at 10 41 38 am" src="https://cloud.githubusercontent.com/assets/1068783/10853637/52a0d532-7ef4-11e5-941b-e3330a3a9daa.png">

Comp:
<img width="502" alt="screen shot 2015-10-30 at 10 49 46 am" src="https://cloud.githubusercontent.com/assets/1068783/10853622/47423b54-7ef4-11e5-88f7-df38df7d01b9.png">
<img width="893" alt="screen shot 2015-10-30 at 10 50 31 am" src="https://cloud.githubusercontent.com/assets/1068783/10853626/4ae640fc-7ef4-11e5-84ed-9b6bc770c4ad.png">

Slightly updated images: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLV3JwR1loQlVTYlU&usp=sharing

Thanks!

**Comment by Pomax** [comment]
interestingly, my browser shows the right spacing - which browser/os did you get the bad spacing on?

**Comment by Pomax** [comment]
Hm, which browser/os did you get the bad spacing on? I get the following on win/FF42 (so I bet it's rems vs px somewhere)

![screenshot 29](https://cloud.githubusercontent.com/assets/177243/10854027/7eb6597e-7ef6-11e5-922b-5fe9b0827f66.png)

**Comment by kristinashu** [comment]
Weird, I'm actually seen it in Firefox, Safari, and Chrome. I have all the latest OS and browser updates. Are you coming in today? Maybe you can take a look.

**Comment by Pomax** [comment]
I am indeed, let's see what's going on at MozYVR

**Comment by Pomax** [comment]
hmm, on OSX 10.9 with FF 42 (no extensions of note) I see this:

![screen shot 2015-11-01 at 2 42 41 pm](https://cloud.githubusercontent.com/assets/177243/10871811/081db70a-80a7-11e5-9718-fec6b998eb0c.png)

**Comment by kristinashu** [comment]
Weird, I'm on OSX 10.11 and FF 42, Safari 9, Chrome 46.0.2490.80 and the bottom is cut off on all three. Looks like it's also cut off on @flukeout computer.

**Comment by flukeout** [comment]
Hey guys - I looked into this a bit and it's happening because the ``.dialog`` class has an explicit height set on it. Remove the explicit height, then add a ``padding-bottom: 1 rem`` on the ``.body`` class in the dialog and all will be well. 

In general, it's a bad idea to set explicit height popups because we'll never really be able to anticipate the content height because of localization.

**Comment by Pomax** [comment]
updated the CSS similar to @flukeout's suggestion (had to put the bottom padding on dialog though, to prevent the publish dialog of goggles itself getting all wonky) and updated the heroku instance. @kristinashu does it still look off for you with those changes?

**Comment by kristinashu** [comment]
Thanks @flukeout and @Pomax it's looking good now.

@Pomax only thing left in this ticket is to update the animal images https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLV3JwR1loQlVTYlU&usp=sharing

**Comment by Pomax** [comment]
we're already using those images though... are you seeing discrepancies anywhere?

**Comment by kristinashu** [comment]
Really minor - fox has a light tail now and the dino is slightly above the skateboard.

**Comment by Pomax** [comment]
redownloaded and pushed, with staging updated too. Closing this issue =D
