### ISSUE TITLE
Image names and folders for FTU activity

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#239]
Something to ponder... currently the file structure is "/img/ftu/top-fox.png" 
During design Cassie mentioned it might be easy for users if it is "/img/top/fox"

@Pomax is it possible to do this?

Dev:
<img width="488" alt="screen shot 2015-10-30 at 10 57 05 am" src="https://cloud.githubusercontent.com/assets/1068783/10853883/cc9e7c80-7ef5-11e5-9e7d-bc8b9ae19d49.png">

Suggested format comp:
<img width="398" alt="screen shot 2015-10-30 at 11 09 35 am" src="https://cloud.githubusercontent.com/assets/1068783/10854077/c80a47a2-7ef6-11e5-89b5-10a58cdeba3c.png">

**Comment by Pomax** [comment]
yeah that should be a relatively straight-forward change.
