### ISSUE TITLE
Set image height in CSS

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#240]
@Pomax this is a good comment from @flukeout - add an image height so the box doesn't collapse while swapping images.

**Comment by flukeout** [comment]
Hmm, one consideration is that if someone uses a random image from the web, it will become distorted. Not sure if we should worry about that case though.

We could also add a height attribute to the image tag, so that if someone uses an external URL they'll be able to adjust it more readily.

**Comment by Pomax** [comment]
Hm, what about this:
```
<figure class="remix-me">
  <img src="/img/top/bird.png">
  <img src="/img/top/bird.png">
  <img src="/img/top/bird.png">
  <style>
    figure.remix-me img { min-height: 140px; }
    figure.remix-me img:first-child { min-height: 200px; }
  </style>
</figure>
```
That way users can, if they really want, mess with the styling as well if they use their own images. On the other hand, exposing more code for what are hopefully edge cases might be detrimental to the experience for users who just want to play with our animals instead.

**Comment by Pomax** [comment]
I tried setting this:
```
<figure class="remix-me">
  <img height="200px" src="/img/animals/top/fox.png">
  <img height="140px" src="/img/animals/middle/bird.png">
  <img height="140px" src="/img/animals/bottom/dinosaur.png">
</figure>
```
However, the goggles does "something" to attribute ordering, so once you click to edit, you get this:
```
<figure class="remix-me">
  <img src="/img/animals/top/fox.png" height="200px">
  <img src="/img/animals/middle/bird.png" height="140px">
  <img src="/img/animals/bottom/dinosaur.png" height="140px">
</figure>
```
which makes things a lot harder to read and remix =(

**Comment by kristinashu** [comment]
Yeah that's starting to look messy. For me the main thing is that the box doesn't collapse when a user deletes the image name. Can that be done without it showing up in the editor?

**Comment by Pomax** [comment]
hmm, we can tap into `img:error:nth-child(...)` to make sure it has the correct height, which will only kick in while people are typing img urls that don't actually work.

**Comment by Pomax** [comment]
CSS, you beautiful mutt.
```
      img[src*='/img/animals'] {
        display: block;
        margin: 0;
        padding: 0;
        width: @imwidth;
        height: 140px;
      }

      img[src*='/img/animals/top'] {
        height: 200px;
      }
    }
```

**Comment by Pomax** [comment]
![screenshot 34](https://cloud.githubusercontent.com/assets/177243/10897618/d10e3dd0-8177-11e5-9032-f8ddcd70ebf2.png)
