### ISSUE TITLE
Add link to install page on FTU page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#241]
As discussed, the comp had a link to the install page but we've decided not to add it.
<img width="1298" alt="screen shot 2015-10-30 at 3 57 39 pm" src="https://cloud.githubusercontent.com/assets/1068783/10859898/0c80bb96-7f1f-11e5-95ef-2d499ca6db55.png">

Instead we're going to add a link to the activate prompt.
<img width="1303" alt="screen shot 2015-10-30 at 4 02 38 pm" src="https://cloud.githubusercontent.com/assets/1068783/10859957/b7b968aa-7f1f-11e5-8076-3efcaba1ce34.png">

**Comment by Pomax** [comment]
link-back added.
