### ISSUE TITLE
FTU bubbles don't line up if user scrolls down

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#245]
For the click to remix image and text instruction bubbles if the user scrolls down then they no longer line up with the text or image.

<img width="1425" alt="screen shot 2015-11-02 at 9 31 17 am" src="https://cloud.githubusercontent.com/assets/1068783/10889068/9ede3758-8144-11e5-9926-1075d189f136.png">

@Pomax any ideas how to fix?

**Comment by Pomax** [comment]
Updated the positioning so that the bubbles are anchored to what they point to, and updated staging.
