### ISSUE TITLE
Update tutorial images

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#246]
@Pomax here are retina pngs for the install page and for the FTU activate bubble (updated step to the dotted border instead of eye icon). Let me know if you need them at a different size.

![goggles-step-1 2x](https://cloud.githubusercontent.com/assets/1068783/10890583/9be6a39c-814d-11e5-84ef-a7d50fdad9f1.png)
![goggles-step-2 2x](https://cloud.githubusercontent.com/assets/1068783/10890585/9c051372-814d-11e5-9970-d58d1575e65c.png)

**Comment by Pomax** [comment]
updated.
