### ISSUE TITLE
Should the "Drag me to your bookmark bar" button be clickable?

### ISSUE THREAD

**Issue by Pomax** [mozilla/goggles.webmaker.org#249]
In order to work as bookmarkable thing, the "drag me" button is a regular link with a javascript: href, so, if you click it the link rather than dragging it, the goggles will activate.

There might be some hackiness we can do to intercept clicks on it, but it's kind of convenient to be able to click it too... @kristinashu @hannahkane what do we want to do here?

**Comment by kristinashu** [comment]
I think it could get annoying if someone is trying to install goggles and then they accidentally click it and activate goggles. Once they're activated there's no way they'll be able to install.

**Comment by hannahkane** [comment]
Agree with @kristinashu - seems like it would be a pretty common pitfall.

**Comment by Pomax** [comment]
wrapped the link in some JS that intercepts clicks, while not interfering with the dragging and activation once a bookmarklet.
