### ISSUE TITLE
improve the looks of the goggles notice bar on published works

### ISSUE THREAD

**Issue by Pomax** [mozilla/goggles.webmaker.org#250]
current look:

![screenshot 35](https://cloud.githubusercontent.com/assets/177243/10897792/4a849da2-8179-11e5-92f0-d7539790417f.png)

@kristinashu  we can probably come up with something more micro-beautiful =D

**Comment by kristinashu** [comment]
@Pomax I'd underline the links instead of using blue and remove the drop shadow. Then it should be good to go!

**Comment by Pomax** [comment]
done and done: http://bramble-staging.s3-website-us-east-1.amazonaws.com/monkeymagic/70
