### ISSUE TITLE
create tutorial images

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#254]
Based on https://github.com/mozilla/teach.mozilla.org/issues/1232

Create different images for each browser and OS. Here's an example on Firefox for Mac https://redpen.io/p/qv1c96b69ffec76998

@Pomax you up for swapping out images and some text (bookmark vs toolbar...) depending on which browser and OS a user is on?

**Comment by Pomax** [comment]
I'd say yes - we can probably use https://www.npmjs.com/package/bowser in a smart way (used in Thimble, too) and we can probably use it for our mobile detection, too.

**Comment by Pomax** [comment]
Using the `us-parser-js` library, we can generate tutorial images using the following naming scheme: `bookmark-OS-BROWSER@2x.png` where OS and BROWSER are lowercase strings. On windows with firefox, chrome, and IE, these filenames get picked:

- bookmark-windows-firefox@2x.png
- bookmark-windows.chrome@2x.png
- bookmark-windows-ie@2x.png

**Comment by Pomax** [comment]
https://github.com/mozilla/goggles.webmaker.org/blob/master/views/homepage/steps.html#L32-L43 houses the text for each os/browser combination, so we can decide how many we want to document

**Comment by Pomax** [comment]
firefox on windows

![firefox](https://cloud.githubusercontent.com/assets/177243/11547580/ea7f1178-9909-11e5-8749-fad23f8cc826.png)

**Comment by Pomax** [comment]
chrome on windows 

![chrome](https://cloud.githubusercontent.com/assets/177243/11547583/f060aaca-9909-11e5-90ad-98556f938aa2.png)

**Comment by Pomax** [comment]
opera on windows

![opera](https://cloud.githubusercontent.com/assets/177243/11547585/f7530544-9909-11e5-9154-523135dd0e58.png)

**Comment by Pomax** [comment]
ie (11) on windows

![ie](https://cloud.githubusercontent.com/assets/177243/11547594/fc7cb8bc-9909-11e5-86d7-3531cbd842ca.png)

**Comment by kristinashu** [comment]
Thanks @Pomax 

Here are the images for Mac: https://drive.google.com/open?id=0B2irLVDJivhLOW1BTkd3a0d0VUk

**Comment by kristinashu** [comment]
@Pomax here are the PNGs for windows: https://drive.google.com/open?id=0B2irLVDJivhLRXRzTUFIaDNnTjQ

**Comment by Pomax** [comment]
pushed out to https://x-ray-goggles-staging.herokuapp.com/ -- we probably need also need a last three "generic" images for when we can't figure out the browser.

**Comment by kristinashu** [comment]
Could show Firefox on windows as the generic? Windows seems more common than Mac with our audience and I guess we should promote FF.

**Comment by Pomax** [comment]
not a bad idea: done! =)

**Comment by kristinashu** [comment]
Nice! Closing.
