### ISSUE TITLE
Implement FTU page updates based on user feedback

### ISSUE THREAD

**Issue by kristinashu** [mozilla/goggles.webmaker.org#256]
Feedback in #253

Comps: https://invis.io/F44O6ZJGY

**Comment by Pomax** [comment]
implemented and running on staging: https://x-ray-goggles-staging.herokuapp.com/ftu

**Comment by kristinashu** [comment]
Coolio! 

Minor typo on the first screen - should say "toolbar"

Noticed all the content is slightly off center, can it be centered? 
<img width="919" alt="screen shot 2015-12-02 at 9 30 07 am" src="https://cloud.githubusercontent.com/assets/1068783/11538960/67e5f126-98d9-11e5-966a-1d8e16b4e5c9.png">
<img width="856" alt="screen shot 2015-12-02 at 9 30 58 am" src="https://cloud.githubusercontent.com/assets/1068783/11538948/54024740-98d9-11e5-93a4-56d999546cc6.png">

Can you style the text in parenthesis smaller and possibly italic? This way it won't look like so much text.
<img width="965" alt="screen shot 2015-12-02 at 9 27 33 am" src="https://cloud.githubusercontent.com/assets/1068783/11538974/7a1af0ee-98d9-11e5-803d-91583d2ead80.png">

I quickly tried it in Mac Firefox, Chrome, Opera and Safari and everything seems good.

@Pomax @hannahkane

**Comment by Pomax** [comment]
for the boxes: can people still read this? we're making the text *very* small at this point

**Comment by Pomax** [comment]
I centered the FTU dialog, but I don't really see an off-centerness for the page content. I checked both FF and Chrome but the content looks centered until you resize the window to "too small to fit it". Maybe we can look at this on your machine.

**Comment by kristinashu** [comment]
Dialog is good now but still a little funny on narrow screen - even without resizing: 

<img width="939" alt="screen shot 2015-12-02 at 11 48 49 am" src="https://cloud.githubusercontent.com/assets/1068783/11542140/b9166dc6-98ea-11e5-9de3-2a78f5630c24.png">

**Comment by hannahkane** [comment]
Typo on "Make a New Animal" - missing word - just *because* you can find...

**Comment by Pomax** [comment]
typo fixed; I've filed the responsiveness issues as to fix under #261

**Comment by Pomax** [comment]
closing as fixed, followup in the ticket noted above
