### ISSUE TITLE
Make tutorial windows highest on z-axis

### ISSUE THREAD

**Issue by hannahkane** [mozilla/goggles.webmaker.org#262]
Just tested with user who repeatedly highlighted the largest div on the tutorial activity page. The tutorial instructions appear *behind* the highlight, making it hard to read/see. Any possibility of moving the tutorial blocks up on the z-axis?

**Comment by Pomax** [comment]
This should now be fixed on https://x-ray-goggles-staging.herokuapp.com/ftu (although if the highligh is blue, it's pretty close to the FTU box's blue. The instructions aren't overlayed though, so the text stays readable)

**Comment by hannahkane** [comment]
w00t. Looks good.
